### ISSUE TITLE
Strain_Code Data

### ISSUE THREAD

**Issue by cnhs6** [kmaterna/Mendocino_Geodesy#1]
Dear kmaterna:
      I want to practice this example 。Can you provide some data about the calculation Strain。for example:input_file="../../GPS_POS_DATA/Velocity_Files/NAM08_pbovelfile_feb2018.txt";

**Comment by kmaterna** [comment]
Hello, I'm glad that you'd like to practice this code!  Thank you for pointing this out.  I have provided a few new things: documentation (readme.md in the 2D_strain directory), and a data file (Example_data/).  I hope it works better now if you pull the latest repo.  Sorry that I didn't make the code usable before this point.  Let me know if there's more issues.

**Comment by kmaterna** [comment]
Also, you should add the Mendocino_Geodesy/GPS_TOOLS/ to your $PYTHONPATH in order for the import statements to work.
